/* Dati delle tecniche. Coordinate in cm, vista dall'alto. Tu (A, rosso) guardi verso est (destra). */
(function(){
const ft=(x,y,a,toe)=>({p:[x,y],a,toe:!!toe});
const D2R=Math.PI/180;
function loc(b,f,s){const a=b.a*D2R;return [b.x+Math.cos(a)*f-Math.sin(a)*s,b.y+Math.sin(a)*f+Math.cos(a)*s]}
// lottatore sdraiato (vista dall'alto): spalle lontane dalle anche, piedi distesi dall'altra parte
function lying(x,y,a,o){const b=Object.assign({x,y,a,lean:46,feet:{}},o||{});
  const L=loc(b,-78,-13),R=loc(b,-78,13);b.feet={L:ft(L[0],L[1],a+180),R:ft(R[0],R[1],a+180)};return b}
const W=o=>Object.assign({lean:8},o);

/* =============== 1. DOPPIA GAMBA =============== */
const dlA0=W({x:125,y:100,a:0,feet:{L:ft(147,85,-8),R:ft(103,118,28)},hL:{to:'B.triR',g:'Mano S sul suo braccio D, dall\'interno, sopra il gomito'},hR:{to:'B.neck',g:'Collar tie: mano D dietro il suo collo, il tuo avambraccio sopra il suo braccio S'}});
const dlB0=W({x:195,y:100,a:180,feet:{L:ft(173,115,188),R:ft(217,82,152)}});
const doubleLeg={
 id:'doppia-gamba',it:'Doppia gamba',en:'Double leg takedown',cat:'Takedown basso',
 intro:'Entri sotto il baricentro, prendi le due gambe dietro le ginocchia e lo porti a terra girando l\'angolo. Qui: guardia sinistra, entrata con il piede S, testa sul lato D.',
 start:{tu:['Guardia sfalsata: piede S avanti, piede D indietro, distanza tra i piedi poco più delle spalle.','Ginocchia piegate, anche basse, schiena dritta, petto sopra le ginocchia, sguardo al suo petto.','Mano D: collar tie dietro il suo collo, passando sopra il suo braccio S.','Mano S: controlla il suo braccio D (gomito/tricipite) dall\'interno.'],
  lui:['Guardia simile, piede S avanti.','Distanza: a contatto con il collar tie, a un braccio da te.']},
 att:[
  {A:dlA0,B:dlB0,t:'Posizione di partenza',
   d:{piedi:'S avanti, D indietro. Peso sulla pianta dei piedi, talloni leggeri.',mani:'D in collar tie sopra il suo braccio S. S sul suo tricipite D dall\'interno.',testa:'Testa alta, fronte vicina alla sua, anche basse.',intento:'Controllare la sua testa per poterlo muovere.'},tempo:null},
  {A:dlA0,B:W({x:190,y:100,a:180,lean:17,head:[6,0],feet:dlB0.feet}),t:'Snap: tira giù la testa',
   arrows:[{from:'B.head',to:['B.head',-24,6],t:'giù e verso di te'}],
   d:{piedi:'Fermi. Al massimo un piccolo passo indietro con il D.',mani:'La D tira di scatto il suo collo in basso. La S tiene il braccio.',testa:'Resti alto: NON scendere con lui.',intento:'Provocare il riflesso: lui si raddrizzerà spingendo in su.'},tempo:'Uno strappo breve e secco.'},
  {A:dlA0,B:W({x:197,y:100,a:180,lean:0,feet:dlB0.feet}),t:'Lui si rialza: è il momento',
   arrows:[{from:'B.chest',to:['B.chest',14,0],k:'b',t:'si rialza'}],
   d:{piedi:'Fermi, già caricati.',mani:'Ancora in presa.',testa:'Sempre bassa sotto la sua: NON salire con lui.',intento:'Quando si raddrizza, le sue anche vanno avanti e le gambe restano aperte. Si parte adesso.'},tempo:'Aspetta la reazione PRIMA di entrare.'},
  {A:W({x:128,y:100,a:0,lean:16,feet:dlA0.feet}),B:W({x:197,y:100,a:180,lean:0,feet:dlB0.feet}),tm:{A:{body:[0,1],hR:[0,.5],hL:[0,.5]}},t:'Cambio di livello',
   d:{piedi:'Fermi. Le ginocchia si piegano.',mani:'Lasci il collar tie MENTRE scendi. Le due mani vanno avanti e in basso, gomiti stretti.',testa:'Su, occhi avanti. Schiena dritta: ti pieghi con le ginocchia, non con la vita.',intento:'Portare le spalle all\'altezza delle sue anche.'},tempo:'Insieme: il collar tie si lascia nello stesso movimento della discesa.'},
  {A:W({x:171,y:112,a:-12,pitch:30,h:50,head:[0,16],knee:{L:[191,104]},feet:{L:ft(150,100,-12,true),R:ft(110,124,10,true)},hL:{to:['B.kneeR',6,0],g:'Mano S dietro il suo ginocchio D'},hR:{to:['B.kneeL',6,0],g:'Mano D dietro il suo ginocchio S'}}),
   B:W({x:204,y:98,a:180,lean:-6,feet:dlB0.feet}),
   tm:{A:{fL:[0,.7],fR:[0,.3],body:[0,.8],hL:[.35,.9],hR:[.35,.9]},B:{body:[.3,1]}},t:'Passo di penetrazione',
   arrows:[{from:[147,85],to:[191,104],k:'a',bend:-.15,t:'ginocchio S tra i suoi piedi'}],
   d:{piedi:'Il piede S fa un passo profondo TRA i suoi piedi, con il piede che avanza per primo (non il piede dietro). Il ginocchio S scende a terra sopra la punta del piede, all\'altezza dei suoi talloni. Il piede D spinge da dietro e resta sulle punte: non tocca terra con il ginocchio.',mani:'S dietro il suo ginocchio D, D dietro il suo ginocchio S (o attorno ai muscoli posteriori della coscia). Tira le ginocchia verso il tuo petto.',testa:'Testa alta, schiena dritta: non ti pieghi alla vita. L\'orecchio D contro il suo fianco S (testa all\'ESTERNO, dal lato della gamba dietro). Gomiti stretti ai fianchi.',intento:'Attraversarlo, non arrivare davanti a lui. La spalla spinge nelle sue anche e lo fa cadere sui talloni mentre le mani tirano le ginocchia. Con il passo profondo resti alto con il busto: se lui fa lo sprawl, la struttura ti regge.'},tempo:'Insieme: ginocchio a terra, testa sul fianco e mani dietro le ginocchia arrivano nello stesso istante.'},
  {A:W({x:186,y:116,a:-10,pitch:34,h:56,head:[0,16],feet:{L:ft(172,102,-6),R:ft(150,134,14,true)},hL:{to:['B.kneeR',6,0]},hR:{to:['B.kneeL',6,0]}}),
   B:W({x:208,y:98,a:180,lean:-10,feet:dlB0.feet}),
   tm:{A:{fR:[0,.55],fL:[.5,1],body:[0,1]}},t:'Il piede dietro sale di lato',
   arrows:[{from:[110,124],to:[150,134],k:'a',bend:.2,t:'piede D: di lato, non dritto'}],
   d:{piedi:'Il piede D (dietro) avanza e si pianta di LATO, accanto al suo piede S, con la punta perpendicolare a lui ("swisher"). Poi il piede S si rialza sotto di te e sei su entrambi i piedi.',mani:'Restano dietro le ginocchia, tirando. Il gomito S va profondo attorno alla gamba.',testa:'Testa alta, orecchio sul suo fianco. Guarda nella direzione in cui vuoi andare.',intento:'Cambiare direzione: non spingi più dritto ma di lato, per tagliare il suo equilibrio. Ti serve essere su due piedi per avere la massima potenza.'},tempo:'In sequenza, ma subito: prima il piede D si pianta di lato, poi ti rialzi dal ginocchio S.'},
  {A:W({x:200,y:121,a:12,pitch:42,h:58,head:[0,16],feet:{L:ft(190,106,10),R:ft(196,140,24)},hL:{to:['B.kneeR',6,0]},hR:{to:['B.kneeL',6,0]}}),
   B:W({x:222,y:104,a:196,lean:-14,feet:{L:ft(204,118,190),R:ft(240,88,164)}}),
   t:'Spingi e gira l\'angolo',
   arrows:[{from:'A.chest',to:[262,150],bend:-.25,t:'verso il lato della testa'}],
   d:{piedi:'Su due piedi, tanti passi corti in avanti, girando verso il lato della testa (a destra, nel tuo caso).',mani:'Tirano le sue ginocchia verso il tuo petto mentre spingi. Le braccia non sollevano: sono ganci.',testa:'La testa guida il movimento: guardi in forte direzione dove vuoi andare. Anche sotto le spalle, schiena dritta. Gomiti in dentro mentre spingi.',intento:'Spingere in avanti e verso il suo dietro-sinistra: ha le gambe tirate verso di te e rimane senza base. Cade di lato o di schiena.'},tempo:'Spinta e rotazione insieme, continue.'},
  {A:W({x:214,y:122,a:24,lean:24,knee:{L:[222,112],R:[212,138]},feet:{L:ft(194,96,24,true),R:ft(180,124,24,true)},hL:{to:'B.hipR'},hR:{to:'B.hipL'}}),
   B:lying(238,130,24),t:'Finisci sopra',
   d:{piedi:'Scendi sulle ginocchia accanto alle sue anche.',mani:'Controlla le anche, poi passa al controllo laterale.',testa:'Petto contro petto, peso su di lui.',intento:'Il punto arriva con il controllo, non con la caduta. Se lui ha un buon equilibrio e non cade: fai un passo attorno con la gamba davanti, fino alla sua gamba lontana, e solleva con le anche (non da terra con la schiena).'},tempo:null}],
 attTips:['Controlla la distanza: tieni la mano tesa. Se non lo raggiungi, nemmeno lui raggiunge te. Parti appena fuori da quella distanza.','Il cambio di livello si fa con le ginocchia, non con la vita. Scendi SOTTO le sue braccia, non dritto verso le gambe.','Il primo passo è con la gamba davanti (non con quella dietro): è più veloce e copre più spazio. Il piede dietro carica e spinge.','Passo PROFONDO: il ginocchio davanti scende a terra sopra la punta del piede, tra i suoi piedi. Così resti alto con il busto e lo sprawl non ti schiaccia.','Schiena dritta, testa alta, anche sotto le spalle: nessuna piega alla vita. Immagina di passare sotto un\'asta e sfiorarla con la schiena.','Il piede dietro sale di LATO ("swisher"), con la punta quasi perpendicolare a lui: cambi direzione, non spingi dritto.','Testa all\'esterno, sullo stesso lato della gamba dietro, e guida il movimento: guardi dove vuoi andare. Atterri con la testa dal lato \'alto\'.','Tira le sue gambe verso di te mentre spingi: spingere soltanto non basta.','Se non cade: passo attorno con la gamba davanti fino alla sua gamba lontana, poi alza con le anche.','Spalle alzate durante l\'entrata: riduce il rischio di ghigliottina.'],
 attErr:['Andare dritto alle gambe: passi dove ci sono le sue braccia e ti blocca.','Passo con la gamba dietro: troppo lento, lui reagisce.','Passo corto: busto inclinato in avanti, facile da schiacciare con lo sprawl.','Mettere a terra il ginocchio sbagliato (quello dietro): perdi la spinta.','Testa all\'interno, in basso o sul lato sbagliato: poco spinta e più rischio.','Piegare la vita invece delle ginocchia.','Finire solo con le braccia, senza spingere dalle gambe.'],
 defIntro:'Lui entra in doppia gamba con il piede S avanti e la testa sul tuo fianco S. Tu: sprawl, whizzer e crossface, poi giri dietro.',
 def:[
  {A:W({x:125,y:100,a:0,feet:dlA0.feet}),B:W({x:195,y:100,a:180,feet:dlB0.feet,hR:{to:'A.neck'},hL:{to:'A.triR'}}),t:'Posizione di partenza',
   d:{piedi:'Guardia S avanti, peso sulle punte.',mani:'Mani attive davanti, gomiti stretti.',testa:'Alta. Guarda le sue anche: il segnale è il suo cambio di livello.',intento:'Essere pronto a reagire.'},tempo:null},
  {A:W({x:125,y:100,a:0,feet:dlA0.feet}),B:W({x:192,y:100,a:180,lean:16,feet:dlB0.feet}),t:'Il segnale: cambia livello',
   d:{piedi:'Pronti a scattare indietro.',mani:'Scendono verso la sua testa e le sue spalle.',testa:'Alta.',intento:'Riconoscere il tiro PRIMA che arrivi.'},tempo:null},
  {A:W({x:122,y:100,a:0,lean:12,feet:dlA0.feet,hL:{to:'B.shR',g:'Mano S sulla sua spalla D'},hR:{to:'B.head',g:'Mano D sulla sua testa'}}),
   B:W({x:152,y:96,a:180,lean:20,head:[0,13],knee:{L:[132,104]},feet:{L:ft(168,104,180,true),R:ft(214,82,152,true)},hL:{to:['A.kneeR',-6,0]},hR:{to:['A.kneeL',-6,0]}}),
   tm:{A:{hL:[0,.5],hR:[0,.5],body:[0,.5]}},t:'Lui entra: mani sulla testa',
   d:{piedi:'Partono indietro (fase successiva).',mani:'D sulla sua testa, S sulla sua spalla D: bloccano l\'entrata.',testa:'Alta, petto avanti.',intento:'Le mani sono la prima difesa: fermano testa e spalle prima delle gambe.'},tempo:'Insieme alla sua entrata, non dopo.'},
  {A:W({x:116,y:100,a:0,lean:24,h:40,pitch:74,feet:{L:ft(58,80,-8,true),R:ft(54,122,8,true)},hL:{to:['B.armpitR',2,0],g:'Whizzer: braccio S sopra il suo braccio D, mano sotto la sua ascella'},hR:{to:'B.shL',g:'Crossface: avambraccio D sul suo viso, mano sulla sua spalla S'}}),
   B:W({x:156,y:98,a:180,lean:26,head:[0,13],knee:{L:[170,108],R:[170,88]},feet:{L:ft(202,108,180,true),R:ft(202,88,180,true)},hL:{to:[100,116]},hR:{to:[100,84]}}),
   tm:{A:{fL:[0,.45],fR:[0,.45],body:[0,.55],hL:[.3,.9],hR:[.3,.9]}},t:'Sprawl',
   arrows:[{from:[147,85],to:[58,80],k:'a',t:'gambe indietro'},{from:'A.c',to:['B.shR',0,8],t:'anche giù sulle sue spalle'}],
   d:{piedi:'Le due gambe scattano indietro, larghe e distese. Resti sulle punte, mai sulle ginocchia.',mani:'Braccio S sopra il suo braccio D (whizzer). Avambraccio D sul suo viso (crossface).',testa:'Alta. Petto e anche pesano sulla sua schiena e sulle spalle.',intento:'Il peso delle anche sulle sue spalle rompe la presa sulle gambe.'},tempo:'Insieme: gambe indietro e anche giù in un unico scatto.'},
  {A:W({x:128,y:128,a:-30,lean:24,h:42,pitch:70,feet:{L:ft(82,128,-30,true),R:ft(96,166,-20,true)},hL:{to:['B.armpitR',2,0]},hR:{to:'B.shL'}}),
   B:W({x:160,y:100,a:180,lean:24,head:[0,4],knee:{L:[172,110],R:[172,90]},feet:{L:ft(204,110,180,true),R:ft(204,90,180,true)},hL:{to:[110,116]},hR:{to:[108,86]}}),
   t:'Crossface e giro',
   arrows:[{from:'B.head',to:['B.head',0,26],t:'gira la sua testa via'},{from:[100,150],to:[170,160],k:'a',bend:.2,t:'giri dal lato del crossface'}],
   d:{piedi:'Cammini in cerchio verso il lato del crossface (il suo fianco S).',mani:'Il crossface gli gira la testa lontano dal tuo fianco. Il whizzer tiene il suo braccio.',testa:'Pesante su di lui.',intento:'Testa girata = presa rotta. Ti apri la strada per la schiena.'},tempo:'In continuo.'},
  {A:W({x:204,y:100,a:180,lean:18,feet:{L:ft(222,124,190),R:ft(236,80,170)},hL:{to:['B.belly',0,0],g:'Braccia attorno alla sua vita'},hR:{to:['B.belly',0,3]}}),
   B:W({x:168,y:100,a:180,lean:24,knee:{L:[180,110],R:[180,90]},feet:{L:ft(208,112,180,true),R:ft(208,88,180,true)},hL:{to:[124,114]},hR:{to:[124,86]}}),
   t:'Gira dietro: 2 punti',
   d:{piedi:'Finisci dietro di lui, gambe larghe.',mani:'Chiudi le mani attorno alla sua vita.',testa:'Sulla sua schiena.',intento:'Lo sprawl ferma il tiro; i punti li fai girando dietro.'},tempo:null}],
 defTips:['Reagisci al cambio di livello, non quando ti ha già preso.','Gambe indietro e anche giù nello stesso istante, sulle punte.','Il whizzer va dal lato della sua testa; il crossface gli gira la testa via.','Non restare fermo nello sprawl: gira dietro.'],
 defErr:['Arretrare in piedi invece di abbassare le anche.','Cadere sulle ginocchia.','Afferrargli il collo cadendo indietro.']};

/* =============== 2. TRASCINAMENTO DEL BRACCIO E CINTURA DA DIETRO =============== */
const adA0=W({x:125,y:100,a:0,feet:{L:ft(147,85,-8),R:ft(103,118,28)}});
const adB0=W({x:192,y:100,a:180,feet:{R:ft(170,84,172),L:ft(214,118,208)},hR:{to:'A.neck',g:'Cerca il collar tie con la mano D'}});
const armDrag={
 id:'arm-drag',it:'Trascinamento del braccio e cintura da dietro',en:'Arm drag to rear body lock & mat return',cat:'Controllo alto',
 intro:'Lui allunga il braccio D. Lo afferri a due mani, lo trascini davanti a te, giri dietro, chiudi le mani in vita e lo riporti a terra. È il caso che descrivevi: "prendere un braccio, ruotarlo, stringerlo ai fianchi da dietro".',
 start:{tu:['Guardia sfalsata: piede S avanti, piede D indietro.','Il tuo piede S è in linea o appena all\'esterno del suo piede D.','Mani davanti, gomiti stretti, distanza da lotta delle mani (avambracci che si toccano).'],
  lui:['Guardia con il piede D avanti.','Allunga la mano D verso il tuo collo (collar tie) o la appoggia sul tuo petto: il braccio D è disteso.']},
 att:[
  {A:adA0,B:adB0,t:'Posizione di partenza',
   d:{piedi:'S avanti, vicino al suo piede D.',mani:'Pronte, gomiti stretti. Puoi invitarlo toccandogli la testa.',testa:'Alta, occhi sul suo petto.',intento:'Vuoi che allunghi il braccio D lontano dal suo fianco.'},tempo:null},
  {A:W({x:125,y:100,a:0,feet:adA0.feet,hL:{to:'B.wrR',g:'Mano S sul suo polso D, dall\'ALTO/esterno: palmo sul dorso del polso, dita sul lato del pollice'},hR:{to:'B.triR',g:'Mano D sul suo tricipite D, SOPRA il gomito, il più vicino possibile all\'ascella; il tuo braccio D passa davanti al tuo corpo'}}),B:adB0,
   tm:{A:{hL:[0,.45],hR:[.25,.9]}},t:'Due prese sullo stesso braccio',
   d:{piedi:'Fermi.',mani:'S sul suo polso D, presa dall\'alto. D attraversa il tuo corpo e afferra il suo tricipite D sopra il gomito. Il gomito D resta basso.',testa:'Alta, petto alto.',intento:'Controllare il braccio in due punti: il polso guida, il tricipite fa leva.'},tempo:'Quasi insieme: prima il polso, la mano D arriva subito dopo.'},
  {A:W({x:136,y:90,a:-32,lean:10,feet:{L:ft(152,56,-40),R:ft(104,116,20)},hL:{to:'B.wrR'},hR:{to:'B.triR'}}),
   B:W({x:160,y:78,a:200,lean:16,feet:{R:ft(140,62,205),L:ft(178,98,195)},hR:{to:['A.hipL',4,0]}}),
   t:'Trascina e fai il passo',
   arrows:[{from:'B.triR',to:'A.hipL',bend:.2,t:'il tricipite verso la tua anca S'},{from:[147,85],to:[152,56],k:'a',t:'piede S fuori dal suo piede D'}],
   d:{piedi:'Il piede S avanza e si pianta all\'esterno del suo piede D, punta verso il suo fianco.',mani:'La D "rema" il suo tricipite in basso e verso la tua anca S. La S spinge il suo polso verso il basso e indietro, verso il suo inguine.',testa:'Petto alto: le tue spalle non scendono sotto le sue.',intento:'La sua spalla viene avanti mentre il polso va via: il braccio attraversa il suo corpo e lui ruota, aprendo il fianco e la schiena. Muovi TE, non solo lui.'},tempo:'Insieme: trascinamento e passo sono un unico movimento.'},
  {A:W({x:178,y:58,a:110,lean:8,feet:{L:ft(196,64,110),R:ft(166,40,120)},hL:{to:'B.wrR'},hR:{to:'B.hipR',g:'La mano D scivola dal tricipite al suo fianco D'}}),
   B:W({x:160,y:80,a:205,lean:18,feet:{R:ft(140,62,205),L:ft(178,98,195)},hR:{to:[150,108]}}),
   tm:{A:{fR:[0,.7],body:[.1,1],fL:[.3,.9]}},t:'Gira l\'angolo',
   arrows:[{from:[104,116],to:[166,40],k:'a',bend:.35,t:'il piede D gira dietro'}],
   d:{piedi:'Il piede D gira dietro di te (perno sul piede S) finché le tue anche sono perpendicolari al suo fianco D.',mani:'S tiene ancora il polso. D scivola dal tricipite al suo fianco D.',testa:'Si avvicina alla sua spalla D.',intento:'Ora sei al suo fianco: lui non ha più il petto davanti a te.'},tempo:'In sequenza: prima il trascinamento, poi l\'angolo.'},
  {A:W({x:192,y:90,a:200,lean:6,head:[0,-6],feet:{L:ft(196,114,200),R:ft(210,72,200)},hL:{to:['B.belly',0,2],g:'La S lascia il polso e gira davanti alla sua pancia'},hR:{to:['B.belly',0,-2],g:'La D lungo la schiena fino alla sua pancia'}}),
   B:W({x:162,y:80,a:200,lean:14,feet:{R:ft(140,62,205),L:ft(178,98,195)}}),
   tm:{A:{hL:[0,.6],hR:[.2,.8],body:[0,1],fL:[.2,.8],fR:[0,.6]}},t:'Dietro: mani attorno alla vita',
   d:{piedi:'Dietro di lui, gambe larghe e piegate.',mani:'Lasci il polso. La S passa davanti alla sua pancia, la D lungo il suo fianco D. Si incontrano sull\'ombelico.',testa:'Orecchio D sulla sua schiena, leggermente sul lato D (il lato del trascinamento).',intento:'La testa sulla schiena gli impedisce di girarsi verso di te.'},tempo:'In sequenza, senza pause.'},
  {A:W({x:186,y:88,a:200,lean:2,head:[0,-6],feet:{L:ft(176,98,200),R:ft(210,72,200)},hL:{to:['B.belly',0,0],g:'Presa a palmo contro palmo (gable grip) all\'altezza dell\'ombelico, sopra le ossa dell\'anca'},hR:{to:['B.belly',0,0]}}),
   B:W({x:162,y:80,a:200,lean:10,feet:{R:ft(140,62,205),L:ft(178,98,195)}}),
   tm:{A:{hL:[0,.4],hR:[0,.4],fL:[.4,1],body:[.4,1]}},t:'Chiudi la presa e le anche sotto',
   d:{piedi:'Il piede S fa un passo corto tra o dietro i suoi piedi.',mani:'Gable grip (palmo contro palmo, pollici chiusi) sull\'ombelico. Stringi le sue anche contro le tue.',testa:'Sulla schiena, petto incollato.',intento:'Le tue anche più basse delle sue: è da lì che lo solleverai.'},tempo:'Prima chiudi le mani, poi abbassi le anche con il passo.'},
  {A:W({x:198,y:100,a:178,lean:12,head:[0,-4],knee:{L:[196,112],R:[196,88]},feet:{L:ft(228,112,178,true),R:ft(228,88,178,true)},hL:{to:['B.belly',0,0]},hR:{to:['B.belly',0,0]}}),
   B:W({x:166,y:100,a:178,lean:26,knee:{L:[176,112],R:[176,88]},feet:{L:ft(206,114,178,true),R:ft(206,90,178,true)},hL:{to:[128,116]},hR:{to:[126,84]}}),
   t:'Solleva, gira e riporta a terra',
   arrows:[{from:[140,62],to:[176,88],k:'b',bend:-.3,t:'le sue gambe spazzate di lato'}],
   d:{piedi:'Esplosione di gambe e anche (non di schiena), poi il piede D fa spazio indietro e scendi in ginocchio con lui.',mani:'La presa non si apre mai.',testa:'Alta, sulla sua schiena.',intento:'Giri verso il suo lato D e spazzi le sue gambe: atterra su anca e ginocchia, i piedi toccano per primi. Mai sulla testa.'},tempo:'Sollevi, giri e accompagni giù in un unico movimento.'}],
 attTips:['"Rema il tricipite verso la tua anca": il trascinamento è verso il basso, non verso l\'alto.','Il passo del piede S e il trascinamento sono un solo movimento.','Afferra sopra il gomito, non l\'avambraccio: sull\'avambraccio non hai leva.','Mani chiuse sull\'ombelico, sopra le anche; testa sulla schiena.','Nel ritorno a terra solleva con le gambe e accompagna giù: nessuna caduta dall\'alto.'],
 attErr:['Tirare solo con le braccia, piedi fermi.','Abbassare la testa davanti a lui: ti prende il collo.','Presa troppo alta sulle costole o troppo bassa sulle cosce.','Restare petto contro il suo fianco invece di andare dietro.'],
 defIntro:'Lui prova a trascinarti il braccio D (sua mano S sul tuo polso, sua D sul tuo tricipite). Prima difesa: non farti trascinare. Seconda: se ti è già dietro, rompi la presa.',
 def:[
  {A:W({x:125,y:100,a:0,feet:{R:ft(147,115,8),L:ft(103,82,-28)},hR:{to:'B.neck',g:'Tu cerchi il collar tie: il braccio D si allunga'}}),B:W({x:192,y:100,a:180,feet:{L:ft(170,116,188),R:ft(214,82,152)}}),t:'Il rischio: braccio disteso',
   d:{piedi:'Guardia piede D avanti.',mani:'Il braccio D allungato verso di lui è l\'occasione che cerca.',testa:'Alta.',intento:'Braccia corte e gomiti dentro: niente da afferrare.'},tempo:null},
  {A:W({x:125,y:100,a:0,feet:{R:ft(147,115,8),L:ft(103,82,-28)},hR:{to:'B.neck'}}),B:W({x:192,y:100,a:180,feet:{L:ft(170,116,188),R:ft(214,82,152)},hL:{to:'A.wrR'},hR:{to:'A.triR'}}),t:'Ti afferra polso e tricipite',
   d:{piedi:'Fermi, base solida.',mani:'Sua S sul tuo polso D, sua D sul tuo tricipite D.',testa:'Alta.',intento:'Reagisci subito, prima che tiri.'},tempo:null},
  {A:W({x:122,y:100,a:0,lean:4,feet:{R:ft(147,115,8),L:ft(103,82,-28)},hR:{to:['A.hipR',8,-2],g:'Gomito D indietro sul tuo fianco, polso che ruota verso il suo pollice'},hL:{to:'B.handL',g:'La tua S strappa la sua mano dal tuo polso'}}),B:W({x:186,y:100,a:180,lean:12,feet:{L:ft(170,116,188),R:ft(214,82,152)},hL:{to:'A.wrR'},hR:{to:'A.triR'}}),
   tm:{A:{hR:[0,.6],hL:[.2,.8],body:[0,.6]}},t:'Riprendi il braccio',
   d:{piedi:'Fermi, anche sotto di te.',mani:'Ruoti il polso D verso il suo pollice (il punto debole della presa) e riporti il gomito D sul tuo fianco. La S stacca la sua mano.',testa:'Alta.',intento:'Il braccio torna corto e attaccato al corpo: il trascinamento non ha più leva.'},tempo:'Insieme: rotazione del polso, gomito indietro e strappo.'},
  {A:W({x:122,y:80,a:14,feet:{R:ft(146,96,20),L:ft(104,60,-14)}}),B:W({x:190,y:100,a:185,feet:{L:ft(170,116,188),R:ft(214,82,152)}}),t:'Gira via dal trascinamento',
   arrows:[{from:[122,100],to:[122,76],k:'a',t:'giri verso la tua S'}],
   d:{piedi:'Fai un passo verso sinistra, lontano dal lato del trascinamento, e rimani di fronte a lui.',mani:'Corte e attive.',testa:'Alta.',intento:'Squadrarti: petto di fronte al suo petto, niente fianco esposto.'},tempo:null},
  {A:W({x:180,y:100,a:0,lean:8,feet:{L:ft(198,84,-5),R:ft(196,118,5)}}),B:W({x:150,y:100,a:0,lean:4,head:[0,-6],feet:{L:ft(140,84,0),R:ft(140,118,0)},hL:{to:['A.belly',0,0]},hR:{to:['A.belly',0,0]}}),t:'Se ti è già dietro',
   d:{piedi:'Situazione nuova: lui è dietro di te con le mani chiuse sulla tua pancia.',mani:'Vanno subito sulle sue mani.',testa:'Alta.',intento:'Agire prima che porti le anche sotto le tue.'},tempo:null},
  {A:W({x:180,y:100,a:0,lean:14,feet:{L:ft(200,70,-20),R:ft(194,132,20)},hL:{to:'B.handR',g:'Due mani sulla sua mano SOPRA: stacca dita/polso'},hR:{to:'B.handR'}}),B:W({x:152,y:100,a:0,lean:4,head:[0,-6],feet:{L:ft(140,84,0),R:ft(140,118,0)},hL:{to:['A.belly',0,0]},hR:{to:['A.belly',0,0]}}),
   tm:{A:{body:[0,.6],fL:[0,.6],fR:[0,.6],hL:[.3,.9],hR:[.3,.9]}},t:'Anche giù, base larga, stacca le mani',
   arrows:[{from:'B.handR',to:['B.handR',0,16],t:'tira la presa in BASSO'}],
   d:{piedi:'Allarga subito la base e abbassa le anche, prima che lui vada sotto di te.',mani:'Le tue due mani sulla sua mano che sta sopra. Staccala tirando verso il basso, via dalla pancia.',testa:'Alta, schiena dritta.',intento:'Più sei basso, meno ti può sollevare.'},tempo:'Prima le anche giù, poi lo strappo delle mani.'},
  {A:W({x:178,y:102,a:180,lean:8,feet:{L:ft(170,120,190),R:ft(176,80,170)},hL:{to:'B.shR'},hR:{to:'B.triL'}}),B:W({x:146,y:100,a:0,lean:4,feet:{L:ft(140,84,0),R:ft(140,118,0)}}),
   tm:{A:{body:[0,1],fL:[0,.7],fR:[.2,1]}},t:'Gira verso di lui',
   d:{piedi:'Ruoti verso il lato della mano che hai staccato e torni di fronte a lui.',mani:'Controlla le sue braccia.',testa:'Alta.',intento:'Di nuovo petto contro petto: sei fuori.'},tempo:null}],
 defTips:['Braccia corte e gomiti dentro: il trascinamento nasce da un braccio lungo.','Contro la presa al polso ruota verso il suo pollice.','Contro la cintura da dietro: anche giù subito, poi stacca la mano sopra tirando in basso.','Gira verso la mano che hai staccato.'],
 defErr:['Tirare il braccio dritto indietro senza ruotare il polso.','Restare dritto con le gambe tese quando ti è dietro.','Girarti prima di aver rotto la presa.']};

/* =============== 3. CINTURA E SGAMBETTO ESTERNO =============== */
const btA0=W({x:170,y:100,a:0,lean:4,head:[0,-12],feet:{L:ft(172,78,-5),R:ft(150,118,20)},hL:{to:['B.waistBack',0,3],g:'Doppio sottobraccio: braccio S sotto la sua ascella D'},hR:{to:['B.waistBack',0,-3],g:'Mani chiuse a palmo contro palmo (gable grip) sulla sua bassa schiena'}});
const btB0=W({x:200,y:100,a:180,lean:4,head:[0,-12],feet:{R:ft(192,80,175),L:ft(214,118,190)},hL:{to:['A.back',0,8]},hR:{to:['A.back',0,-8]}});
const bodyLock={
 id:'cintura-sgambetto',it:'Cintura e sgambetto esterno',en:'Body lock outside trip',cat:'Proiezione alta',
 intro:'Dal clinch chiudi le mani dietro la sua schiena, carichi il suo peso sul tallone D, blocchi quel tallone da fuori con la tua gamba S e lo spingi in diagonale. Qui: sgambetto con la gamba S sulla sua gamba D, testa sul suo lato D.',
 start:{tu:['Petto contro petto, il tuo petto un po\' più alto del suo, anche vicine sotto le sue.','Doppio sottobraccio: le tue braccia sotto le sue ascelle, gomiti stretti ai suoi fianchi.','Mani chiuse sulla sua bassa schiena (cintura), palmo contro palmo. Dita non intrecciate.','Orecchio S contro il suo lato D (clavicola/mascella).','Piede S all\'altezza del suo piede D, ginocchia piegate.'],
  lui:['In piedi, quasi frontale.','Il suo piede D, carico di peso, è il bersaglio.']},
 att:[
  {A:btA0,B:btB0,t:'Posizione di partenza: la cintura',
   d:{piedi:'S all\'altezza del suo piede D, D indietro. Ginocchia piegate.',mani:'Doppio sottobraccio, mani chiuse a palmo contro palmo sulla sua bassa schiena (all\'altezza della cintura, non sulle scapole).',testa:'Orecchio S sul suo lato D: è il lato che attaccherai.',intento:'Controllare le sue anche, non le spalle.'},tempo:null},
  {A:W(Object.assign({},btA0,{x:177,lean:2})),B:W(Object.assign({},btB0,{x:198,lean:-4})),t:'Anche contro anche',
   arrows:[{from:'B.c',to:'A.c',t:'tira le sue anche contro le tue'}],
   d:{piedi:'Fermi.',mani:'Stringi con gli avambracci: le sue anche vengono contro le tue.',testa:'Spinge leggermente in avanti e verso il basso sul suo lato D.',intento:'I suoi talloni si alleggeriscono: comincia a perdere la base.'},tempo:null},
  {A:W(Object.assign({},btA0,{x:177,lean:2,a:-6})),B:W(Object.assign({},btB0,{x:198,lean:-4,a:194})),t:'Carica il peso sul suo tallone D',
   arrows:[{from:'B.shL',to:'B.shR',bend:.45,t:'giralo come un volante'}],
   d:{piedi:'Fermi.',mani:'Ruoti il suo busto verso il suo lato D, come se girassi un volante.',testa:'La testa sul suo lato D guida la rotazione.',intento:'Il suo peso scende sul tallone D: quel piede non può più muoversi.'},tempo:'In sequenza: prima la presa, poi il carico, poi il passo.'},
  {A:W(Object.assign({},btA0,{x:184,y:102,lean:2,a:-6,feet:{L:ft(172,78,-5),R:ft(204,104,10)}})),B:W(Object.assign({},btB0,{x:199,lean:-4,a:194})),
   tm:{A:{fR:[0,.8],body:[.3,1]}},t:'Passo di base con il piede D',
   arrows:[{from:[150,118],to:[204,104],k:'a',bend:.15,t:'piede D tra i suoi piedi'}],
   d:{piedi:'Il piede D avanza TRA i suoi piedi, un po\' verso il suo piede S, sotto il suo centro. Ginocchio piegato.',mani:'La presa resta chiusa.',testa:'Ferma sul suo lato D.',intento:'Questa è la tua base: senza di lei, quando agganci, cadi tu.'},tempo:'Il passo arriva un attimo PRIMA dell\'aggancio.'},
  {A:W(Object.assign({},btA0,{x:194,y:94,lean:10,a:-14,feet:{L:ft(207,72,-10),R:ft(204,104,10)}})),
   B:W(Object.assign({},btB0,{x:214,y:88,a:204,lean:-16,feet:{R:ft(192,80,175),L:ft(224,122,195)}})),
   tm:{A:{fL:[0,.55],body:[.25,1]},B:{body:[.3,1],fL:[.5,1]}},t:'Aggancia e spingi: un solo tempo',
   arrows:[{from:[172,78],to:[207,72],k:'a',bend:-.35,t:'gamba S fuori, dietro il suo tallone D'},{from:'A.chest',to:[252,58],t:'in diagonale sopra il suo tallone D'}],
   d:{piedi:'Il piede S scivola lungo l\'ESTERNO del suo piede D e si ferma DIETRO il suo tallone. Polpaccio contro polpaccio. Gamba quasi dritta e bassa: è un blocco, non un calcio.',mani:'Continuano a tirare le sue anche contro di te.',testa:'Petto e testa spingono in diagonale, verso il suo dietro-destra.',intento:'Spingi verso il punto dove non ha un piede (la "terza gamba"). Il suo piede D non può fare il passo indietro: cade.'},tempo:'Insieme: anche dentro + aggancio + spinta sono un solo tempo ("passo-aggancio-spinta").'},
  {A:W({x:206,y:84,a:-30,lean:22,head:[0,-12],knee:{L:[214,74],R:[198,104]},feet:{L:ft(180,72,-30,true),R:ft(170,104,-30,true)},hL:{to:['B.waistBack',0,3]},hR:{to:['B.waistBack',0,-3]}}),
   B:lying(232,72,-30),t:'Atterra sopra',
   d:{piedi:'Cadi con lui, ginocchio S già oltre la sua gamba D.',mani:'La presa si apre SOLO dopo l\'atterraggio.',testa:'Resta sul suo lato D, vicino all\'orecchio.',intento:'Petto contro petto, anche pesanti. Non lo lanci: cadi con lui, senza spingergli la testa sul tappeto.'},tempo:null}],
 attTips:['"Anche contro anche": senza contatto delle anche lo sgambetto scivola.','La testa sta sullo stesso lato della gamba che attacchi.','"Tallone dietro tallone": blocco corto, non una spazzata alta.','Spingi in diagonale sopra il suo tallone, non dritto all\'indietro.'],
 attErr:['Presa alta sulle scapole: non controlli le anche.','Agganciare prima di aver caricato il peso sulla sua gamba.','Gamba d\'aggancio alzata: resti su un piede.','Lasciare la presa prima di toccare terra.'],
 defIntro:'Lui cerca la cintura e lo sgambetto esterno con la sua gamba S sulla tua gamba D. Prima difesa: non lasciargli chiudere le mani. Seconda: togli la gamba e allarga la base.',
 def:[
  {A:W({x:160,y:100,a:0,lean:16,head:[0,10],feet:{L:ft(176,80,-5),R:ft(130,120,20)},hR:{to:['B.back',0,10],g:'Sottobraccio D: il tuo braccio D sotto la sua ascella S'},hL:{to:['B.chest',0,-10],g:'Avambraccio S sulla sua clavicola (frame)'}}),
   B:W({x:198,y:100,a:180,lean:10,feet:{L:ft(186,118,185),R:ft(216,82,170)},hL:{to:'A.sideR'},hR:{to:'A.sideL'}}),t:'Anche indietro, un sottobraccio tuo',
   d:{piedi:'Anche indietro, gambe sfalsate e piegate.',mani:'Prendi almeno un sottobraccio (qui il D). L\'avambraccio S fa da "telaio" sulla sua clavicola.',testa:'Alta, dentro.',intento:'Distanza tra le anche = niente cintura.'},tempo:null},
  {A:W({x:174,y:100,a:0,lean:4,head:[0,10],feet:{L:ft(182,78,-5),R:ft(170,122,10)},hR:{to:['B.back',0,10]},hL:{to:['B.chest',0,-10]}}),
   B:W({x:198,y:100,a:180,lean:4,head:[0,12],feet:{L:ft(186,118,185),R:ft(216,82,170)},hL:{to:['A.waistBack',0,-3]},hR:{to:['A.waistBack',0,3]}}),t:'Se ti chiude la cintura',
   d:{piedi:'Piedi quasi paralleli: il tuo piede D è il bersaglio.',mani:'Il tuo sottobraccio resta dentro.',testa:'Alta.',intento:'Sapere qual è il lato attaccato: quello della sua testa.'},tempo:null},
  {A:W({x:176,y:100,a:6,lean:2,head:[0,10],feet:{L:ft(182,78,-5),R:ft(170,122,10)},hR:{to:['B.back',0,10]},hL:{to:['B.chest',0,-10]}}),
   B:W({x:192,y:104,a:186,lean:8,head:[0,12],feet:{L:ft(158,130,180),R:ft(194,92,175)},hL:{to:['A.waistBack',0,-3]},hR:{to:['A.waistBack',0,3]}}),
   tm:{B:{fR:[0,.5],fL:[.3,1]}},t:'Lui aggancia il tuo tallone D',
   d:{piedi:'La sua gamba S ti blocca da fuori il tallone D.',mani:'Il sottobraccio tiene.',testa:'Alta.',intento:'Reagisci appena senti il polpaccio: è un blocco, non ha ancora spinto.'},tempo:null},
  {A:W({x:156,y:96,a:4,lean:16,head:[0,10],feet:{L:ft(146,70,-15),R:ft(136,128,20)},hR:{to:['B.back',0,10]},hL:{to:['B.chest',0,-10]}}),
   B:W({x:190,y:104,a:186,lean:16,head:[0,12],feet:{L:ft(158,130,180),R:ft(194,92,175)},hL:{to:['A.sideR']},hR:{to:['A.sideL']}}),
   tm:{A:{fR:[0,.5],fL:[.3,.8],body:[.2,1]}},t:'Togli la gamba e allarga la base',
   arrows:[{from:[170,122],to:[136,128],k:'a',t:'gamba D su e indietro'},{from:[182,78],to:[146,70],k:'a',t:'S indietro e fuori'}],
   d:{piedi:'Sfili la gamba D sollevandola indietro, fuori dall\'aggancio. Il piede S va indietro e in fuori per coprire la diagonale.',mani:'Il sottobraccio resta; l\'avambraccio S spinge.',testa:'Alta, anche indietro (sprawl delle anche).',intento:'Coprire il punto in cui voleva farti cadere: ora hai di nuovo due piedi.'},tempo:'Prima la gamba D, subito dopo la S.'},
  {A:W({x:158,y:100,a:0,lean:10,head:[0,10],feet:{L:ft(176,80,-5),R:ft(134,120,20)},hR:{to:['B.back',0,10]},hL:{to:['B.armpitR'],g:'Ri-pummel: secondo sottobraccio, o whizzer'}}),
   B:W({x:198,y:100,a:180,lean:10,feet:{L:ft(186,118,185),R:ft(216,82,170)},hL:{to:'A.shR'},hR:{to:'A.shL'}}),t:'Ri-pummel e squadrati',
   d:{piedi:'Torni in guardia sfalsata.',mani:'Riprendi i sottobracci dal lato dell\'aggancio.',testa:'Alta.',intento:'Hai il controllo del clinch: ora attacchi tu.'},tempo:null}],
 defTips:['Anche indietro e almeno un sottobraccio tuo.','Se ti chiude, abbassati e allarga la base.','Gamba agganciata: sollevala indietro, non irrigidirla.','Il piede libero copre la diagonale (la "terza gamba").'],
 defErr:['Gambe tese e vicine.','Petto contro petto senza sottobracci.','Appoggiare una mano dietro mentre cadi.']};

window.TECHS=[doubleLeg,armDrag,bodyLock];
})();
